# Generated by Django 4.2.20 on 2025-05-09 03:54

from django.db import migrations

from django.contrib.auth.models import User
import os

def create_superuser(apps, schema_editor):
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin')
    
    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(username, email, password)

class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_blockchainnode_transaction_smartcontract_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
